# Generated by Django 4.1 on 2022-10-30 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('plant', models.CharField(choices=[('PD', 'Padi'), ('JG', 'Jagung'), ('KT', 'Kacang Tanah'), ('SK', 'Singkong'), ('UJ', 'Ubi Jalar'), ('KE', 'Kentang'), ('WO', 'Wortel'), ('BW', 'Bawang'), ('TM', 'Tomat'), ('PS', 'Pisang'), ('JR', 'Jeruk')], max_length=2)),
                ('amount_of_plants', models.IntegerField()),
                ('amount_of_u_needed', models.FloatField()),
                ('amount_of_s_needed', models.FloatField()),
                ('amount_of_k_needed', models.FloatField()),
                ('expected_yield', models.FloatField()),
                ('gross_income', models.FloatField()),
                ('net_income', models.FloatField()),
                ('user_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
