# Generated by Django 4.1 on 2022-10-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('plant', models.CharField(choices=[('PD', 'Rice'), ('JG', 'Corn'), ('KT', 'Peanut'), ('SK', 'Cassava'), ('UJ', 'Sweet Potato'), ('KE', 'Potato'), ('WO', 'Carrot'), ('BW', 'Onion'), ('TM', 'Tomato'), ('PS', 'Banana'), ('JR', 'Orange')], max_length=2)),
                ('amount_of_plants', models.IntegerField()),
                ('amount_of_u_needed', models.FloatField()),
                ('amount_of_s_needed', models.FloatField()),
                ('amount_of_k_needed', models.FloatField()),
                ('expected_yield', models.IntegerField()),
                ('gross_income', models.IntegerField()),
                ('net_income', models.IntegerField()),
                ('user_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
