# Generated by Django 4.1 on 2022-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='username',
            field=models.TextField(default='NULL'),
        ),
    ]
