# Generated by Django 4.1 on 2022-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.TextField(default='FARMLAND'),
        ),
    ]
